# Generated by Django 4.0.3 on 2022-03-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('write', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime(2022, 3, 6, 19, 22, 44, 411619))),
                ('viewcnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='seops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
