# Generated by Django 4.0.3 on 2022-03-07 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0002_bbs_seops'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bbs',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 16, 3, 58, 335966)),
        ),
    ]
