# Generated by Django 4.0.3 on 2022-03-07 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0004_alter_bbs_regdate_alter_data_csv_data_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 17, 40, 8, 248100)),
        ),
    ]
