# Generated by Django 4.0.3 on 2022-03-07 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0005_alter_bbs_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_qa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_q', models.CharField(max_length=1000)),
                ('data_a', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='bbs',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 17, 49, 7, 187292)),
        ),
    ]
