# Generated by Django 4.0.3 on 2022-03-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0006_data_qa_alter_bbs_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_a', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='data_q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_q', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Bbs',
        ),
        migrations.DeleteModel(
            name='data_qa',
        ),
        migrations.DeleteModel(
            name='seops',
        ),
    ]
