# Generated by Django 4.0.3 on 2022-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0007_data_a_data_q_delete_bbs_delete_data_qa_delete_seops'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_an', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_qu', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='data_a',
        ),
        migrations.DeleteModel(
            name='data_q',
        ),
    ]
