# Generated by Django 4.0.3 on 2022-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0008_answer_question_delete_data_a_delete_data_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_a', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='data_que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_q', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
