# Generated by Django 4.0.3 on 2022-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0009_data_ans_data_que_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_csv_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_q', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='data_ans',
        ),
        migrations.DeleteModel(
            name='data_que',
        ),
    ]
