# Generated by Django 4.0.3 on 2022-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0010_data_csv_question_delete_data_ans_delete_data_que'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_csv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='data_csv_question',
        ),
    ]
