# Generated by Django 4.0.3 on 2022-03-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0012_data_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_csv',
        ),
        migrations.DeleteModel(
            name='data_csv2',
        ),
    ]
